// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsExports = {
  Auth: {
    identityPoolId: "YOUR-IDENTITY-POOL-ID",
    region: "YOUR-REGION",
    userPoolId: "YOUR-USERPOOL-ID",
    userPoolWebClientId: "YOUR-APPID",
  },
};

export default awsExports;
