// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

import { Auth } from "@aws-amplify/auth";

const awsExports = {
    "Auth": {
        "identityPoolId": 'YOUR-IDENTITY-POOL-ID',
        "region": 'YOUR-REGION',
        "userPoolId": 'YOUR-USERPOOL-ID',
        "userPoolWebClientId": 'YOUR-APPID',
    },
};

export default awsExports;
